### ISSUE TITLE
Default value for "qml-ls-client.qmllsPath": "qmlls"

### ISSUE THREAD

**Issue by mateusz-plociennik** [Derevin/QML-LS-Client#1]
I installed qt with homebrew (Mac), so the qmlls should be available in $PATH. 

In terminal I can do: 
```
$ type qmlls
qmlls is /opt/homebrew/bin/qmlls
```

**Comment by Derevin** [comment]
Added `qmlls` as a default for `qmllsPath` config variable in 1.0.0. Thanks for the suggestion.
