### ISSUE TITLE
workspace.didChangeWatchedFiles feature missing

### ISSUE THREAD

**Issue by mateusz-plociennik** [Derevin/QML-LS-Client#2]
I am getting the following error:
qt.languageserver.server: "registration of file udates failed, will miss file changes done outside the editor due to error -32603 Request client/registerCapability failed with message: No feature implementation for workspace.didChangeWatchedFiles found. Registration failed."

**Comment by Derevin** [comment]
Sadly this error is at the `qmlls` side, nothing can be done about it in this client extension
